[package]
name = "wallet-cli"
version = "0.1.0"
authors = ["Shuyu WANG <andelf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2", features = ["yaml"] }
grpc = "0.6.1"
protobuf = "2"
futures = "0.1"
futures-cpupool = "0.1"
serde_json = "1.0"
hex = "0.4"

proto = { path = "../proto" }
