[package]
name = "proto2"
version = "0.1.0"
authors = ["andelf <andelf@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
prost = "0.6"
# Any
prost-types = "0.6"

[build-dependencies]
prost-build = "0.6"
