[package]
name = "proto2"
version = "0.1.0"
authors = ["andelf <andelf@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
prost = "0.6"
# Any
prost-types = "0.6"
hex = "0.4"
byteorder = "1.3.4"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
prost-build = "0.6"
