[package]
name = "chain"
version = "0.1.0"
authors = ["andelf <andelf@gmail.com>"]
edition = "2018"

[dependencies]
prost = "0.6"
byteorder = '1.3'
sha2 = '0.9'
rayon = "1.3"
proto2 = { path = '../proto2' }
primitive-types = "0.7"
crypto = { path = "../crypto" }
merkle-tree = { path = '../merkle-tree' }
