[package]
name = "keys"
version = "0.1.0"
authors = ["Shuyu WANG <andelf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.1"
hex = "0.4"
sha2 = "0.8"
sha3 = "0.8"
parity-secp256k1 = "0.7"
