[package]
name = "keys"
version = "0.1.0"
authors = ["OpenTron Developers <info@opentron.org>"]
edition = "2018"

[dependencies]
base58 = "0.1"
hex = "0.4"
sha2 = "0.9"
sha3 = "0.9"
digest = "0.9"
libsecp256k1 = "0.3"
# locked with libsecp256k1
rand = "0.7"
