name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install protobuf
              run: sudo apt-get install protobuf-compiler libprotobuf-dev
            - name: Download ztron-params
              run: |
                mkdir ztron-params
                cd ztron-params
                wget -q https://github.com/tronprotocol/java-tron/raw/master/framework/src/main/resources/params/sapling-output.params
                wget -q https://github.com/tronprotocol/java-tron/raw/master/framework/src/main/resources/params/sapling-spend.params
            - name: Build walletd
              run: cargo build -p walletd
            - name: Build wallet-cli
              run: cargo build -p wallet-cli
            - name: Run tests
              run: cargo test --exclude node-cli --workspace
